steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/slangtrap-model', '-f', 'Dockerfile', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/slangtrap-dev3']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy slangtrap-dev3 \
          --image gcr.io/$PROJECT_ID/slangtrap-dev3 \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated

# Store images
#images:
 # - 'gcr.io/$PROJECT_ID/slangtrap-model'
